version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "crystal"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"

  # Disable Docker updates since this is not a Docker project
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "never"
